on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '23'

      - name: Build with Maven
        run: |
          cd eight-queens
          chmod +x mvnw
          ./mvnw package

      - name: Build Docker image
        run: |
          docker build -t eight-queens-app .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker tag eight-queens-app ${{ secrets.DOCKER_USERNAME }}/eight-queens-app
          docker push ${{ secrets.DOCKER_USERNAME }}/eight-queens-app
          docker push ghcr.io/${{ github.repository_owner | toLowerCase }}/eight-queens-app:latest